package cloudbackup

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// Anything a user owns has to leave with them. A table that accumulates user
// rows but never reaches Payload is data a pilot cannot take to another
// installation and cannot get back from their own backup — which is how
// contacts, custom currency rules, notification preferences and the flight
// baseline all ended up outside the export.
//
// Nothing links the schema to the payload, so this test does: every table in
// db/migrations must be classified below, and a new one fails the build until
// somebody decides which side it falls on.
//
// Adding a table means adding a line here. Choose exported (name the Payload
// section that carries it) or exempt (say why it is not the user's to take).

// exported maps a table to the Payload section carrying its rows.
var exported = map[string]string{
	"flights":                  "Flights",
	"flight_crew_members":      "Flights[].CrewMembers",
	"aircraft":                 "Aircraft",
	"licenses":                 "Licenses[].License",
	"class_ratings":            "Licenses[].ClassRatings",
	"credentials":              "Credentials",
	"contacts":                 "Contacts",
	"custom_currency_rules":    "CustomCurrencyRules",
	"notification_preferences": "NotificationPreferences",
	"flight_baselines":         "FlightBaseline",
}

// exempt maps a table to the reason its rows are not part of a user's backup.
var exempt = map[string]string{
	"users":                     "the account itself; a restore targets an existing account",
	"admin_audit_log":           "operator record of admin actions, not user content",
	"backup_destinations":       "credentials for this installation's storage; encrypted at rest and meaningless elsewhere",
	"backup_runs":               "audit log of backup attempts against this installation",
	"deletion_tombstones":       "sync bookkeeping; regenerated by triggers",
	"document_files":            "binary attachments, served by their own endpoints rather than inlined in a JSON backup",
	"email_delivery_events":     "operator delivery log",
	"email_suppressions":        "operator bounce list, keyed by address not account",
	"email_verification_tokens": "short-lived credential",
	"flight_imports":            "history of past import runs, not logbook content",
	"flight_sessions":           "in-progress tap-to-log capture, discarded once the flight is saved",
	"flight_signatures":         "instructor attestations bound to this installation's signing links and keys",
	"idempotency_keys":          "short-lived request bookkeeping",
	"notification_log":          "record of mail already sent",
	"oidc_handoff_codes":        "short-lived credential",
	"oidc_identities":           "binding to this installation's identity provider",
	"oidc_login_states":         "short-lived credential",
	"password_reset_tokens":     "short-lived credential",
	"refresh_tokens":            "session credential",
	"system_announcements":      "operator content, not user content",
	"webauthn_credentials":      "passkeys are bound to this origin and cannot be transferred",
	"webauthn_sessions":         "short-lived ceremony state",
}

// One alternation so statements are replayed in source order: migration 51
// drops webauthn_sessions and recreates it in the same file, and matching by
// category would apply the drop last.
var tableStmtRe = regexp.MustCompile(
	`(?i)CREATE TABLE (?:IF NOT EXISTS )?([a-z_][a-z0-9_]*)` +
		`|ALTER TABLE ([a-z_][a-z0-9_]*) RENAME TO ([a-z_][a-z0-9_]*)` +
		`|DROP TABLE (?:IF EXISTS )?([a-z_][a-z0-9_]*)`)

// schemaTables replays the up-migrations in order and returns the tables the
// schema ends up with.
func schemaTables(t *testing.T) []string {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join("..", "..", "..", "db", "migrations", "*.up.sql"))
	if err != nil {
		t.Fatalf("glob migrations: %v", err)
	}
	if len(paths) == 0 {
		t.Fatal("no migrations found")
	}
	sort.Strings(paths)

	tables := map[string]bool{}
	for _, path := range paths {
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		sql := stripComments(string(body))
		for _, m := range tableStmtRe.FindAllStringSubmatch(sql, -1) {
			switch {
			case m[1] != "":
				tables[m[1]] = true
			case m[2] != "":
				delete(tables, m[2])
				tables[m[3]] = true
			case m[4] != "":
				delete(tables, m[4])
			}
		}
	}

	out := make([]string, 0, len(tables))
	for name := range tables {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func stripComments(sql string) string {
	lines := strings.Split(sql, "\n")
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		if idx := strings.Index(line, "--"); idx >= 0 {
			line = line[:idx]
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

func TestEveryTableIsExportedOrExempt(t *testing.T) {
	for _, table := range schemaTables(t) {
		_, isExported := exported[table]
		_, isExempt := exempt[table]
		switch {
		case isExported && isExempt:
			t.Errorf("table %q is listed as both exported and exempt", table)
		case !isExported && !isExempt:
			t.Errorf("table %q is not classified: add it to `exported` naming the "+
				"Payload section that carries it, or to `exempt` with the reason "+
				"it is not the user's to take", table)
		}
	}
}

// The classification is only worth as much as its accuracy, so the tables it
// claims are exported must actually be reachable from Payload.
func TestExportedTablesHaveAPayloadSection(t *testing.T) {
	body, err := os.ReadFile("payload.go")
	if err != nil {
		t.Fatalf("read payload.go: %v", err)
	}
	src := string(body)
	for table, section := range exported {
		field := section
		if idx := strings.IndexAny(field, "[."); idx >= 0 {
			field = field[:idx]
		}
		if !strings.Contains(src, "\t"+field+" ") && !strings.Contains(src, "\t"+field+"\t") {
			t.Errorf("table %q claims Payload section %q, but payload.go has no field %q",
				table, section, field)
		}
	}
}

// A table that no longer exists must not linger in either list.
func TestClassificationHasNoStaleTables(t *testing.T) {
	live := map[string]bool{}
	for _, table := range schemaTables(t) {
		live[table] = true
	}
	for _, list := range []map[string]string{exported, exempt} {
		for table := range list {
			if !live[table] {
				t.Errorf("table %q is classified but no longer in the schema", table)
			}
		}
	}
}
