// Command rulesgen generates Go from vocabulary.yaml, messages/keys.yaml and the catalogue:
// engine/zz_metrics_gen.go (the metric dispatch the engine must implement), gen/constants.go
// (rule ids, message keys, metric names) and one test file per rule under gen/ that runs
// the rule's cases. Run it with `go generate ./...`.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/fjaeckel/ninerlog-rules/engine"
)

const header = "// Code generated by rulesgen. DO NOT EDIT.\n\n"

func main() {
	root := flag.String("root", ".", "module root (the directory holding vocabulary.yaml)")
	flag.Parse()
	cat, err := engine.LoadCatalogue(*root)
	if err != nil {
		log.Fatal(err)
	}
	if err := generate(*root, cat); err != nil {
		log.Fatal(err)
	}
}

func generate(root string, cat *engine.Catalogue) error {
	if err := write(filepath.Join(root, "engine", "zz_metrics_gen.go"), metricsFile(cat.Vocabulary)); err != nil {
		return err
	}
	genDir := filepath.Join(root, "gen")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return err
	}
	old, _ := filepath.Glob(filepath.Join(genDir, "rule_*_test.go"))
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	if err := write(filepath.Join(genDir, "constants.go"), constantsFile(cat)); err != nil {
		return err
	}
	if err := write(filepath.Join(genDir, "helpers_test.go"), helpersFile()); err != nil {
		return err
	}
	for _, r := range cat.Rules {
		name := filepath.Join(genDir, "rule_"+snake(r.ID)+"_test.go")
		if err := write(name, ruleTestFile(r)); err != nil {
			return err
		}
	}
	return nil
}

func write(path string, src []byte) error {
	out, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("%s: %w\n%s", path, err, src)
	}
	return os.WriteFile(path, out, 0o644)
}

// ident turns a dotted, dashed or snake name into an exported Go identifier part.
func ident(s string) string {
	var b strings.Builder
	upper := true
	var prev rune
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper && unicode.IsDigit(r) && unicode.IsDigit(prev) {
			b.WriteRune('_')
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
		} else {
			b.WriteRune(r)
		}
		upper, prev = false, r
	}
	return b.String()
}

func snake(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return r
		}
		return '_'
	}, s)
}

func sortedMetricNames(v *engine.Vocabulary) []string {
	names := make([]string, 0, len(v.Metrics))
	for n := range v.Metrics {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func metricsFile(v *engine.Vocabulary) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("package engine\n\n")
	b.WriteString("// metricImpl lists one method per vocabulary metric; metrics must implement all.\n")
	b.WriteString("type metricImpl interface {\n")
	names := sortedMetricNames(v)
	for _, n := range names {
		fmt.Fprintf(&b, "\tmetric%s(*%s) mv\n", ident(n), itemType(v.Metrics[n]))
	}
	b.WriteString("}\n\nvar _ metricImpl = metrics{}\n\n")
	b.WriteString("// flightMetricFuncs maps flight metric names to implementations.\n")
	b.WriteString("var flightMetricFuncs = map[string]func(*Flight) mv{\n")
	for _, n := range names {
		if itemType(v.Metrics[n]) == "Flight" {
			fmt.Fprintf(&b, "\t%q: metrics{}.metric%s,\n", n, ident(n))
		}
	}
	b.WriteString("}\n\n// eventMetricFuncs maps event metric names to implementations.\n")
	b.WriteString("var eventMetricFuncs = map[string]func(*Event) mv{\n")
	for _, n := range names {
		if itemType(v.Metrics[n]) == "Event" {
			fmt.Fprintf(&b, "\t%q: metrics{}.metric%s,\n", n, ident(n))
		}
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func itemType(m engine.MetricDef) string {
	if m.Source == "events" {
		return "Event"
	}
	return "Flight"
}

func constantsFile(cat *engine.Catalogue) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("// Package gen holds generated constants and the per-rule case tests.\npackage gen\n\n")
	b.WriteString("// Rule ids.\nconst (\n")
	ids := make([]string, 0, len(cat.Rules))
	for _, r := range cat.Rules {
		ids = append(ids, r.ID)
	}
	sort.Strings(ids)
	for _, id := range ids {
		fmt.Fprintf(&b, "\tRule%s = %q\n", ident(id), id)
	}
	b.WriteString(")\n\n// Message keys.\nconst (\n")
	keys := make([]string, 0, len(cat.Keys.Keys))
	for _, k := range cat.Keys.Keys {
		keys = append(keys, k.Key)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "\tKey%s = %q\n", ident(k), k)
	}
	b.WriteString(")\n\n// Metric names.\nconst (\n")
	for _, n := range sortedMetricNames(cat.Vocabulary) {
		fmt.Fprintf(&b, "\tMetric%s = %q\n", ident(n), n)
	}
	b.WriteString(")\n\n// RuleIDs lists every catalogue rule id.\nvar RuleIDs = []string{\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "\tRule%s,\n", ident(id))
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func helpersFile() []byte {
	return []byte(header + `package gen_test

import (
	"sync"
	"testing"

	"github.com/fjaeckel/ninerlog-rules/engine"
)

var catalogue = sync.OnceValues(func() (*engine.Catalogue, error) { return engine.LoadCatalogue("..") })

// runRuleCases runs every case in cases/<id>/ and reports each difference.
func runRuleCases(t *testing.T, id string) {
	t.Helper()
	cat, err := catalogue()
	if err != nil {
		t.Fatal(err)
	}
	cases, err := engine.LoadCases("..", id)
	if err != nil {
		t.Fatal(err)
	}
	if len(cases) == 0 {
		t.Skip("no cases yet")
	}
	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			for _, d := range engine.RunCase(cat, c).Diffs {
				t.Errorf("%s: %s", c.File, d)
			}
		})
	}
}
`)
}

func ruleTestFile(r *engine.Rule) []byte {
	return []byte(fmt.Sprintf(header+`package gen_test

import "testing"

func TestRule_%s(t *testing.T) { runRuleCases(t, %q) }
`, snake(r.ID), r.ID))
}
