//go:build e2e

package e2e_test

import (
	"context"
	"testing"

	"github.com/fjaeckel/pilotlog-api/internal/config"
	"github.com/fjaeckel/pilotlog-api/internal/repository/postgres"
	"github.com/fjaeckel/pilotlog-api/internal/service"
	"github.com/fjaeckel/pilotlog-api/internal/testutil"
	"github.com/fjaeckel/pilotlog-api/pkg/hash"
	"github.com/fjaeckel/pilotlog-api/pkg/jwt"
	"github.com/gin-gonic/gin"









































































































































































































































}	})		}			t.Errorf("Expected status 200, got %d", w.Code)		if w.Code != 200 {		w := client.POST("/api/v1/auth/login", loginPayload)		}			"password": "NewPassword456!",			"email":    "reset@example.com",		loginPayload := map[string]string{	t.Run("Login with new password after reset", func(t *testing.T) {	})		}			t.Errorf("Expected status 200 (security), got %d", w.Code)		if w.Code != 200 {		w := client.POST("/api/v1/auth/password-reset", resetPayload)		}			"email": "nonexistent@example.com",		resetPayload := map[string]string{	t.Run("Request reset for non-existent email", func(t *testing.T) {	})		}			t.Errorf("Expected status 200, got %d", w.Code)		if w.Code != 200 {		w := client.POST("/api/v1/auth/password-reset", resetPayload)		}			"email": "reset@example.com",		resetPayload := map[string]string{	t.Run("Request password reset", func(t *testing.T) {	}		t.Fatalf("Failed to register user: status %d", w.Code)	if w.Code != 201 {	w := client.POST("/api/v1/auth/register", registerPayload)	}		"name":     "Reset Test User",		"password": "OldPassword123!",		"email":    "reset@example.com",	registerPayload := map[string]string{	ctx := context.Background()	router, client := setupTestServer(t)	}		t.Skip("Skipping e2e test")	if testing.Short() {func TestPasswordResetFlowE2E(t *testing.T) {}	})		}			t.Errorf("Expected status 401, got %d", w.Code)		if w.Code != 401 {		w := client.GET("/api/v1/users/me")		client.SetAuthToken("")	t.Run("Access protected endpoint without token fails", func(t *testing.T) {	})		}			t.Errorf("Expected status 200, got %d", w.Code)		if w.Code != 200 {		w = client.GET("/api/v1/users/me")		client.SetAuthToken(accessToken)		accessToken := response["accessToken"].(string)		client.ParseJSON(w, &response)		var response map[string]interface{}		w := client.POST("/api/v1/auth/login", loginPayload)		}			"password": "SecurePass123!",			"email":    "e2e@example.com",		loginPayload := map[string]string{	t.Run("Access protected endpoint with valid token", func(t *testing.T) {	})		}			t.Error("Expected new accessToken")		if refreshResponse["accessToken"] == nil {		client.ParseJSON(w, &refreshResponse)		var refreshResponse map[string]interface{}		}			t.Errorf("Expected status 200, got %d", w.Code)		if w.Code != 200 {		w = client.POST("/api/v1/auth/refresh", refreshPayload)		}			"refreshToken": refreshToken,		refreshPayload := map[string]string{		refreshToken := loginResponse["refreshToken"].(string)		client.ParseJSON(w, &loginResponse)		var loginResponse map[string]interface{}		w := client.POST("/api/v1/auth/login", loginPayload)		}			"password": "SecurePass123!",			"email":    "e2e@example.com",		loginPayload := map[string]string{	t.Run("Refresh token flow", func(t *testing.T) {	})		}			t.Errorf("Expected status 401, got %d", w.Code)		if w.Code != 401 {		w := client.POST("/api/v1/auth/login", loginPayload)		}			"password": "WrongPassword",			"email":    "e2e@example.com",		loginPayload := map[string]string{	t.Run("Login with wrong password fails", func(t *testing.T) {	})		client.SetAuthToken(accessToken)		accessToken := response["accessToken"].(string)		}			t.Error("Expected accessToken in response")		if response["accessToken"] == nil {		client.ParseJSON(w, &response)		var response map[string]interface{}		}			t.Errorf("Expected status 200, got %d", w.Code)		if w.Code != 200 {		w := client.POST("/api/v1/auth/login", loginPayload)		}			"password": "SecurePass123!",			"email":    "e2e@example.com",		loginPayload := map[string]string{	t.Run("Login with correct credentials", func(t *testing.T) {	})		}			t.Errorf("Expected status 409, got %d", w.Code)		if w.Code != 409 {		w := client.POST("/api/v1/auth/register", registerPayload)	t.Run("Register duplicate email fails", func(t *testing.T) {	})		}			t.Error("Expected refreshToken in response")		if response["refreshToken"] == nil {		}			t.Error("Expected accessToken in response")		if response["accessToken"] == nil {		client.ParseJSON(w, &response)		var response map[string]interface{}		}			t.Errorf("Expected status 201, got %d", w.Code)		if w.Code != 201 {		w := client.POST("/api/v1/auth/register", registerPayload)	t.Run("Register new user", func(t *testing.T) {	}		"name":     "E2E Test User",		"password": "SecurePass123!",		"email":    "e2e@example.com",	registerPayload := map[string]string{	ctx := context.Background()	router, client := setupTestServer(t)	}		t.Skip("Skipping e2e test")	if testing.Short() {func TestAuthFlowE2E(t *testing.T) {}	return router, testutil.NewAPITestClient(t, router)	router := gin.New()	gin.SetMode(gin.TestMode)	)		hashService,		jwtMaker,		passwordResetRepo,		refreshTokenRepo,		userRepo,	authService := service.NewAuthService(	passwordResetRepo := postgres.NewPasswordResetTokenRepository(db)	refreshTokenRepo := postgres.NewRefreshTokenRepository(db)	userRepo := postgres.NewUserRepository(db)	hashService := hash.New()	jwtMaker := jwt.NewMaker(cfg.JWT.AccessSecret, cfg.JWT.RefreshSecret)	}		},			RefreshTokenExpiry: 7 * 24 * 3600,			AccessTokenExpiry:  15 * 60,			RefreshSecret:      "test_refresh_secret_key_for_testing",			AccessSecret:       "test_access_secret_key_for_testing",		JWT: config.JWTConfig{	cfg := &config.Config{	})		testutil.TeardownTestDB(t, db)	t.Cleanup(func() {	db := testutil.SetupTestDB(t)	t.Helper()func setupTestServer(t *testing.T) (*gin.Engine, *testutil.APITestClient) {)